#!/bin/sh

for i in $(./bin/disco -v | grep 'DISCO\|DDFS' | tr -d ' \t')
do
    eval "export $i"
done

export DISCO_SETTINGS="DISCO_PROXY,DISCO_DEBUG,DISCO_MASTER_ROOT,DDFS_PUT_MAX,DISCO_TEST_PURGE,DISCO_PORT,DISCO_JOB_OWNER,GRAPHITE_HOST,DISCO_PROXY_PID,DISCO_TEST_HOST,DISCO_TEST_DISCODB,DISCO_NAME,DDFS_PARANOID_DELETE,DISCO_PROXY_PORT,DDFS_WRITE_TOKEN,DISCO_TEST_PORT,DISCO_MASTER_HOME,DDFS_BLOB_REPLICAS,DDFS_PUT_PORT,DISCO_ERLANG,DDFS_GC_INITIAL_WAIT,DISCO_ROOT,DDFS_READ_TOKEN,DISCO_DATA,DISCO_USER,DISCO_SCHEDULER_ALPHA,DISCO_MASTER_CONFIG,DISCO_ROTATE_LOG,DISCO_FLAGS,DISCO_PROFILE,DISCO_PROXY_ENABLED,DISCO_LOG_DIR,DDFS_TAG_MIN_REPLICAS,DISCO_SCHEDULER,DDFS_TAG_REPLICAS,DISCO_HTTPD,DISCO_EVENTS,DISCO_SETTINGS_FILE,DISCO_MASTER_HOST,DISCO_PID_DIR,DDFS_ABSOLUTE_SPACE,DISCO_PROXY_CONFIG,DDFS_GC_BALANCE_THRESHOLD,DISCO_WWW_ROOT,DDFS_ROOT,DISCO_TEST_PROFILE,DDFS_DATA,DISCO_MASTER,DISCO_HOME,DISCO_WORKER_MAX_MEM,DISCO_GC_AFTER,DDFS_SPACE_AWARE,SYSTEMD_ENABLED,DISCO_ULIMIT,DDFS_GET_MAX,DISCO_SETTINGS"

erl -- -sname disco_8989_slave@localhost -pa /master/ebin/ -pa /master/deps/mochiweb/ebin -pa /master/deps/lager/ebin -pa /master/deps/plists/ebin -s slave slave_start  disco_8989_master@sandbox slave_waiter_0  -f -master disco_8989_master@sandbox -noshell -detached

